
version: '3.7'

services:
  mongen_donations:
    container_name: mongen_donations_dev
    build:
      context: ${HOME}/mongen/mongen-donations
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://mongen:123123@db/mongen_donations_db
    volumes:
      - '${HOME}/mongen/mongen-donations:/app'
    ports:
      - '8000:80'
    restart: on-failure
    links:
      - db
    depends_on:
      - db

  db:
      image: "postgres:12"
      container_name: mongen_donations_db_dev
      environment:
        - POSTGRES_USER=mongen
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=mongen_donations_db
      ports:
        - '5433:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U mongen -d mongen_donations_db"]
        interval: 10s
        timeout: 5s
        retries: 5
